### ISSUE TITLE
Move "getting started" project to cucumber repository

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba-getting-started#3]
# Summary

This "getting started"-repository is an "example app" for users who are interested in getting started with aruba - so this essentially belongs to the aruba project.

Since I was not sure, where to place this repository I created this organisation first.

@aslakhellesoy @mattwynne @olleolleolle @mvz What do you think, does it makes sense to move it to https://github.com/cucumber?

**Comment by olleolleolle** [comment]
Moving it to the cucumber org sounds good to me.

**Comment by mvz** [comment]
Yes, I think that makes sense.
